adicionando slides de strings
filrpe/treinamento-OBI-2023 pull request #145
Opened 2023-04-29 22:38 UTC by FerrariusF

2023-05-08 02:04 UTC, callmerockett commented
@alex-repo-alves

2023-05-16 00:14 UTC, alex-repo-alves commented
Ok

2023-05-16 00:25 UTC, filiperib98 commented
Ok

2023-05-16 00:26 UTC, filiperib98 commented
ok

2023-05-19 03:06 UTC, callmerockett requested changes
Alguns pontos para corrigir:

1. "Strings" por si só não são estruturas de dados, por definição strings são cadeias de caracteres terminadas com o caractere `'\0'`. A história é outra se estivermos falando de std::string, que é um *container* que podemos utilizar ao incluir a biblioteca \<string\> (normalmente incluída por meio de outras bibliotecas) no nosso programa.
2. A sugestão referente ao ponto anterior então é: Alterar o título do slide, usar um ou dois slides pra conceituar strings e diferenciar de um array de caracteres genérico, e então introduzir std::string de c++, que é o que usamos na prática nas competições.
3. Remover o primeiro exemplo do slide 7, aquilo é undefined behavior, e não é bom nem entrar nesse tipo de discussão com quem tá aprendendo. Mais detalhes podem ser vistos nesses links: [aqui](https://stackoverflow.com/questions/65373289/does-string-in-c-have-no-out-of-bound-exeption-error) e [aqui](https://stackoverflow.com/questions/2397984/undefined-unspecified-and-implementation-defined-behavior) .
4. No segundo exemplo do slide 8, não é "acréscimo" de strings, é **concatenação** de strings. Pode comentar que é juntar as duas strings em uma, obecendo a ordem em que elas foram operadas/concatenadas.
5. No slide 9, que tá escrito "a string é computada até encontrar o término de uma palavra contínua", com o *cin* ela é computada até um espaço em branco ou uma quebra de linha, fica melhor se especificar em vez de falar "término".

2023-06-11 15:46 UTC, merged