Adicionando slides de monotonic pointers
filrpe/treinamento-OBI-2023 pull request #152
Opened 2023-05-06 19:23 UTC by FerrariusF

2023-05-08 02:05 UTC, callmerockett commented
@alex-repo-alves

2023-05-16 00:14 UTC, alex-repo-alves commented
Ok

2023-05-16 00:47 UTC, callmerockett commented
@filiperib98

2023-05-19 02:24 UTC, callmerockett requested changes
Vou comentar as alterações por slide pra facilitar:

- slide 2: Nesse problema, tem uma informação muito importante que sem ela o problema fica um pouco mais complicado, que é que **todos os números são distintos**. É importante citar isso no enunciado do problema.

- slide 3: aqui tu pode substituir a frase "Lembrando que os números não podem fazer par consigo e que o par de um com o outro é o mesmo que o outro com esse um" por "Lembrando que os números não podem fazer par consigo mesmo, e que cada par só é contado uma vez, não importando a ordem dos elementos, por exemplo: o par (1, 2) é igual ao par (2, 1)"

- slide 7: o vetor do exemplo da "Maneira Busca binária" não está ordenado, tem que ajeitar a figura.

2023-06-23 01:11 UTC, callmerockett commented
Adicionando logo, e a edição vai ser feita posteriormente

2023-06-23 01:11 UTC, merged