Adicionando slides de busca binária
filrpe/treinamento-OBI-2023 pull request #153
Opened 2023-05-06 19:26 UTC by FerrariusF

2023-05-08 02:05 UTC, callmerockett commented
@alex-repo-alves

2023-05-16 00:13 UTC, alex-repo-alves commented
Ok

2023-05-16 00:45 UTC, callmerockett commented
@filiperib98

2023-05-19 01:59 UTC, callmerockett requested changes
Aonde tem "pior hipótese" no slide, é melhor trocar pra "pior caso possível". E um bônus seria explicar por que é o pior caso possível. Exemplo: no problema do ogro o pior caso possível pra um algoritmo *naive* (que passa linearmente nas faixas) é quando a força do ogro tá na última faixa.

Embora pareça besteira, saber identificar o pior cenário possível para uma abordagem é uma habilidade bem desejável. E ter contato com esse tipo de discussão ajuda a desenvolver essa habilidade.

2023-06-11 15:50 UTC, merged